<?php

use App\Administrador\Permiso;
use Illuminate\Database\Seeder;

class PermisosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        #EMPRESA
            $permisoModulo = new Permiso;
            $permisoModulo->nombre = "Empresas";
            $permisoModulo->slug = "modulo.empresa.index";
            $permisoModulo->tipo = "Modulo";
            $permisoModulo->imagen = "default.png";
            $permisoModulo->referencia = null;
            $permisoModulo->descripcion = "Ver Modulo de Empresa";
            $permisoModulo->save();
            $permisos = new Permiso;
            $permisos->nombre = "Listar empresas";
            $permisos->slug = "submodulo.empresa.list";
            $permisos->tipo = "Submodulo";
            $permisos->imagen = "default.png";
            $permisos->referencia = $permisoModulo->id;
            $permisos->descripcion = "Listar empresas del sistema";
            $permisos->save();
            $permisos = new Permiso;
            $permisos->nombre = "Crear empresa";
            $permisos->slug = "submodulo.empresa.store";
            $permisos->tipo = "Submodulo";
            $permisos->imagen = "default.png";
            $permisos->referencia = $permisoModulo->id;
            $permisos->descripcion = "Crear empresas del sistema";
            $permisos->save();
            $permisos = new Permiso;
            $permisos->nombre = "Detalles empresa";
            $permisos->slug = "submodulo.empresa.show";
            $permisos->tipo = "Submodulo";
            $permisos->imagen = "default.png";
            $permisos->referencia = $permisoModulo->id;
            $permisos->descripcion = "Detalles de empresa del sistema";
            $permisos->save();
            $permisos = new Permiso;
            $permisos->nombre = "Editar empresa";
            $permisos->slug = "submodulo.empresa.edit";
            $permisos->tipo = "Submodulo";
            $permisos->imagen = "default.png";
            $permisos->referencia = $permisoModulo->id;
            $permisos->descripcion = "Editar empresa del sistema";
            $permisos->save();
            $permisos = new Permiso;
            $permisos->nombre = "Actualizar empresa";
            $permisos->slug = "submodulo.empresa.update";
            $permisos->tipo = "Submodulo";
            $permisos->imagen = "default.png";
            $permisos->referencia = $permisoModulo->id;
            $permisos->descripcion = "Actualizar empresa del sistema";
            $permisos->save();
            $permisos = new Permiso;
            $permisos->nombre = "Eliminar empresa";
            $permisos->slug = "submodulo.empresa.delete";
            $permisos->tipo = "Submodulo";
            $permisos->imagen = "default.png";
            $permisos->referencia = $permisoModulo->id;
            $permisos->descripcion = "Eliminar empresa del sistema";
            $permisos->save();
        #END EMPRESA

        #USUARIOS
            $permisoModulo = new Permiso;
            $permisoModulo->nombre = "Usuarios";
            $permisoModulo->slug = "modulo.usuario.index";
            $permisoModulo->tipo = "Modulo";
            $permisoModulo->imagen = "default.png";
            $permisoModulo->referencia = null;
            $permisoModulo->descripcion = "Ver Modulo de Usuario";
            $permisoModulo->save();
            $permisos = new Permiso;
            $permisos->nombre = "Listar usuarios";
            $permisos->slug = "submodulo.usuario.list";
            $permisos->tipo = "Submodulo";
            $permisos->imagen = "default.png";
            $permisos->referencia = $permisoModulo->id;
            $permisos->descripcion = "Listar usuarios del sistema";
            $permisos->save();
            $permisos = new Permiso;
            $permisos->nombre = "Crear usuario";
            $permisos->slug = "submodulo.usuario.store";
            $permisos->tipo = "Submodulo";
            $permisos->imagen = "default.png";
            $permisos->referencia = $permisoModulo->id;
            $permisos->descripcion = "Crear usuarios del sistema";
            $permisos->save();
            $permisos = new Permiso;
            $permisos->nombre = "Detalles usuario";
            $permisos->slug = "submodulo.usuario.show";
            $permisos->tipo = "Submodulo";
            $permisos->imagen = "default.png";
            $permisos->referencia = $permisoModulo->id;
            $permisos->descripcion = "Detalles de usuario del sistema";
            $permisos->save();
            $permisos = new Permiso;
            $permisos->nombre = "Editar usuario";
            $permisos->slug = "submodulo.usuario.edit";
            $permisos->tipo = "Submodulo";
            $permisos->imagen = "default.png";
            $permisos->referencia = $permisoModulo->id;
            $permisos->descripcion = "Editar usuarios del sistema";
            $permisos->save();
            $permisos = new Permiso;
            $permisos->nombre = "Actualizar usuario";
            $permisos->slug = "submodulo.usuario.update";
            $permisos->tipo = "Submodulo";
            $permisos->imagen = "default.png";
            $permisos->referencia = $permisoModulo->id;
            $permisos->descripcion = "Actualizar usuarios del sistema";
            $permisos->save();
            $permisos = new Permiso;
            $permisos->nombre = "Eliminar usuario";
            $permisos->slug = "submodulo.usuario.delete";
            $permisos->tipo = "Submodulo";
            $permisos->imagen = "default.png";
            $permisos->referencia = $permisoModulo->id;
            $permisos->descripcion = "Eliminar usuarios del sistema";
            $permisos->save();
        #END USUARIOS

        #ROLES
            $permisoModulo = new Permiso;
            $permisoModulo->nombre = "roles";
            $permisoModulo->slug = "modulo.rol.index";
            $permisoModulo->tipo = "Modulo";
            $permisoModulo->imagen = "default.png";
            $permisoModulo->referencia = null;
            $permisoModulo->descripcion = "Ver Modulo de rol";
            $permisoModulo->save();
            $permisos = new Permiso;
            $permisos->nombre = "Listar roles";
            $permisos->slug = "submodulo.rol.list";
            $permisos->tipo = "Submodulo";
            $permisos->imagen = "default.png";
            $permisos->referencia = $permisoModulo->id;
            $permisos->descripcion = "Listar roles del sistema";
            $permisos->save();
            $permisos = new Permiso;
            $permisos->nombre = "Crear rol";
            $permisos->slug = "submodulo.rol.store";
            $permisos->tipo = "Submodulo";
            $permisos->imagen = "default.png";
            $permisos->referencia = $permisoModulo->id;
            $permisos->descripcion = "Crear roles del sistema";
            $permisos->save();
            $permisos = new Permiso;
            $permisos->nombre = "Detalles rol";
            $permisos->slug = "submodulo.rol.show";
            $permisos->tipo = "Submodulo";
            $permisos->imagen = "default.png";
            $permisos->referencia = $permisoModulo->id;
            $permisos->descripcion = "Detalles de rol del sistema";
            $permisos->save();
            $permisos = new Permiso;
            $permisos->nombre = "Editar rol";
            $permisos->slug = "submodulo.rol.edit";
            $permisos->tipo = "Submodulo";
            $permisos->imagen = "default.png";
            $permisos->referencia = $permisoModulo->id;
            $permisos->descripcion = "Editar roles del sistema";
            $permisos->save();
            $permisos = new Permiso;
            $permisos->nombre = "Actualizar rol";
            $permisos->slug = "submodulo.rol.update";
            $permisos->tipo = "Submodulo";
            $permisos->imagen = "default.png";
            $permisos->referencia = $permisoModulo->id;
            $permisos->descripcion = "Actualizar roles del sistema";
            $permisos->save();
            $permisos = new Permiso;
            $permisos->nombre = "Eliminar rol";
            $permisos->slug = "submodulo.rol.delete";
            $permisos->tipo = "Submodulo";
            $permisos->imagen = "default.png";
            $permisos->referencia = $permisoModulo->id;
            $permisos->descripcion = "Eliminar roles del sistema";
            $permisos->save();
        #END ROLES

        #MULTICONSULTA
            $permisoModulo = new Permiso;
            $permisoModulo->nombre = "Multiconsulta";
            $permisoModulo->slug = "modulo.multiconsulta.index";
            $permisoModulo->tipo = "Modulo";
            $permisoModulo->imagen = "default.png";
            $permisoModulo->referencia = null;
            $permisoModulo->descripcion = "Ver Modulo de Multiconsulta";
            $permisoModulo->save();
            $permisos = new Permiso;
            $permisos->nombre = "Ver Averia";
            $permisos->slug = "submodulo.multiconsulta.averia.view";
            $permisos->tipo = "Submodulo";
            $permisos->imagen = "default.png";
            $permisos->referencia = $permisoModulo->id;
            $permisos->descripcion = "Ver boton averia de Multiconsulta";
            $permisos->save();
            $permisos = new Permiso;
            $permisos->nombre = "Ver Mapa";
            $permisos->slug = "submodulo.multiconsulta.mapa.view";
            $permisos->tipo = "Submodulo";
            $permisos->imagen = "default.png";
            $permisos->referencia = $permisoModulo->id;
            $permisos->descripcion = "Ver boton mapa de Multiconsulta";
            $permisos->save();
            $permisos = new Permiso;
            $permisos->nombre = "Ver Datos intraway";
            $permisos->slug = "submodulo.multiconsulta.intraway.view";
            $permisos->tipo = "Submodulo";
            $permisos->imagen = "default.png";
            $permisos->referencia = $permisoModulo->id;
            $permisos->descripcion = "Ver boton intraway en Multiconsulta";
            $permisos->save();
            $permisos = new Permiso;
            $permisos->nombre = "Ver Niveles RFC CM";
            $permisos->slug = "submodulo.multiconsulta.niveles-rfc.view";
            $permisos->tipo = "Submodulo";
            $permisos->imagen = "default.png";
            $permisos->referencia = $permisoModulo->id;
            $permisos->descripcion = "Ver boton niveles RFC CM en Multiconsulta";
            $permisos->save();
            $permisos = new Permiso;
            $permisos->nombre = "Ver Diagnostico masivo";
            $permisos->slug = "submodulo.multiconsulta.diagnostico-masivo.view";
            $permisos->tipo = "Submodulo";
            $permisos->imagen = "default.png";
            $permisos->referencia = $permisoModulo->id;
            $permisos->descripcion = "Ver boton diagnostico masivo en Multiconsulta";
            $permisos->save();
            $permisos = new Permiso;
            $permisos->nombre = "Ver Cable Modem";
            $permisos->slug = "submodulo.multiconsulta.cm.view";
            $permisos->tipo = "Submodulo";
            $permisos->imagen = "default.png";
            $permisos->referencia = $permisoModulo->id;
            $permisos->descripcion = "Ver boton cable modem en Multiconsulta";
            $permisos->save();
            $permisos = new Permiso;
            $permisos->nombre = "Ver estado del CM";
            $permisos->slug = "submodulo.multiconsulta.cm.estado.view";
            $permisos->tipo = "Submodulo";
            $permisos->imagen = "default.png";
            $permisos->referencia = $permisoModulo->id;
            $permisos->descripcion = "Ver estado del CM en Multiconsulta";
            $permisos->save();
            $permisos = new Permiso;
            $permisos->nombre = "Ver DHCP del CM";
            $permisos->slug = "submodulo.multiconsulta.cm.dhcp.view";
            $permisos->tipo = "Submodulo";
            $permisos->imagen = "default.png";
            $permisos->referencia = $permisoModulo->id;
            $permisos->descripcion = "Ver DHCP del CM en Multiconsulta";
            $permisos->save();
            $permisos = new Permiso;
            $permisos->nombre = "Ver Wifi Vecinos del CM";
            $permisos->slug = "submodulo.multiconsulta.cm.wifi-vecinos.view";
            $permisos->tipo = "Submodulo";
            $permisos->imagen = "default.png";
            $permisos->referencia = $permisoModulo->id;
            $permisos->descripcion = "Ver WIFI Vecinos del CM en Multiconsulta";
            $permisos->save();
            $permisos = new Permiso;
            $permisos->nombre = "Ver Diagnostico del CM";
            $permisos->slug = "submodulo.multiconsulta.cm.diagnostico.view";
            $permisos->tipo = "Submodulo";
            $permisos->imagen = "default.png";
            $permisos->referencia = $permisoModulo->id;
            $permisos->descripcion = "Ver Diagnostico del CM en Multiconsulta";
            $permisos->save();
            $permisos = new Permiso;
            $permisos->nombre = "Configurar Wifi del CM";
            $permisos->slug = "submodulo.multiconsulta.cm.config-wifi.view";
            $permisos->tipo = "Submodulo";
            $permisos->imagen = "default.png";
            $permisos->referencia = $permisoModulo->id;
            $permisos->descripcion = "Configurar el Wifi del CM en Multiconsulta";
            $permisos->save();
            $permisos = new Permiso;
            $permisos->nombre = "Configurar Wifi del CM";
            $permisos->slug = "submodulo.multiconsulta.cm.config-wifi.view";
            $permisos->tipo = "Submodulo";
            $permisos->imagen = "default.png";
            $permisos->referencia = $permisoModulo->id;
            $permisos->descripcion = "Configurar el Wifi del CM en Multiconsulta";
            $permisos->save();
            $permisos = new Permiso;
            $permisos->nombre = "UPnP del CM";
            $permisos->slug = "submodulo.multiconsulta.cm.upnp.view";
            $permisos->tipo = "Submodulo";
            $permisos->imagen = "default.png";
            $permisos->referencia = $permisoModulo->id;
            $permisos->descripcion = "UpnP del CM en Multiconsulta";
            $permisos->save();
            $permisos = new Permiso;
            $permisos->nombre = "DMZ del CM";
            $permisos->slug = "submodulo.multiconsulta.cm.dmz.view";
            $permisos->tipo = "Submodulo";
            $permisos->imagen = "default.png";
            $permisos->referencia = $permisoModulo->id;
            $permisos->descripcion = "DMZ del CM en Multiconsulta";
            $permisos->save();
            $permisos = new Permiso;
            $permisos->nombre = "Mapeo de Puertos del CM";
            $permisos->slug = "submodulo.multiconsulta.cm.port-maping.view";
            $permisos->tipo = "Submodulo";
            $permisos->imagen = "default.png";
            $permisos->referencia = $permisoModulo->id;
            $permisos->descripcion = "Mapeo de puertos del CM en Multiconsulta";
            $permisos->save();
            $permisos = new Permiso;
            $permisos->nombre = "Ver opción Reset Scraping del CM";
            $permisos->slug = "submodulo.multiconsulta.cm.reset-scraping.view";
            $permisos->tipo = "Submodulo";
            $permisos->imagen = "default.png";
            $permisos->referencia = $permisoModulo->id;
            $permisos->descripcion = "Ver opción (pestaña) reset scraping del CM en Multiconsulta";
            $permisos->save();
            $permisos = new Permiso;
            $permisos->nombre = "Restart Simple Scraping del CM";
            $permisos->slug = "submodulo.multiconsulta.cm.reset-scraping.simple.view";
            $permisos->tipo = "Submodulo";
            $permisos->imagen = "default.png";
            $permisos->referencia = $permisoModulo->id;
            $permisos->descripcion = "Reseto simple scraping del CM en Multiconsulta";
            $permisos->save();
            $permisos = new Permiso;
            $permisos->nombre = "Restart Fabrica Scraping del CM";
            $permisos->slug = "submodulo.multiconsulta.cm.reset-scraping.fabrica.view";
            $permisos->tipo = "Submodulo";
            $permisos->imagen = "default.png";
            $permisos->referencia = $permisoModulo->id;
            $permisos->descripcion = "Reseto de fabrica scraping del CM en Multiconsulta";
            $permisos->save();
            $permisos = new Permiso;
            $permisos->nombre = "Gráfica del Trafico Down";
            $permisos->slug = "submodulo.multiconsulta.grafico-trafico-down.view";
            $permisos->tipo = "Submodulo";
            $permisos->imagen = "default.png";
            $permisos->referencia = $permisoModulo->id;
            $permisos->descripcion = "Ver grafica del Trafico Down en Multiconsulta";
            $permisos->save();
            $permisos = new Permiso;
            $permisos->nombre = "Reset del CM Intraway";
            $permisos->slug = "submodulo.multiconsulta.reset-cm-intraway.view";
            $permisos->tipo = "Submodulo";
            $permisos->imagen = "default.png";
            $permisos->referencia = $permisoModulo->id;
            $permisos->descripcion = "Ver boton del reset CM por Intraway en Multiconsulta";
            $permisos->save();
            $permisos = new Permiso;
            $permisos->nombre = "Reset Decos Intraway";
            $permisos->slug = "submodulo.multiconsulta.reset-decos-intraway.view";
            $permisos->tipo = "Submodulo";
            $permisos->imagen = "default.png";
            $permisos->referencia = $permisoModulo->id;
            $permisos->descripcion = "Ver boton del reset Decos por Intraway en Multiconsulta";
            $permisos->save();
            $permisos = new Permiso;
            $permisos->nombre = "Velocidad del CM Intraway";
            $permisos->slug = "submodulo.multiconsulta.velocidad-cm-intraway.view";
            $permisos->tipo = "Submodulo";
            $permisos->imagen = "default.png";
            $permisos->referencia = $permisoModulo->id;
            $permisos->descripcion = "Ver boton cambio de celovidad del CM por Intraway en Multiconsulta";
            $permisos->save();
            $permisos = new Permiso;
            $permisos->nombre = "Cambio de ScopeGroup del CM Intraway";
            $permisos->slug = "submodulo.multiconsulta.scopegroup-cm-intraway.view";
            $permisos->tipo = "Submodulo";
            $permisos->imagen = "default.png";
            $permisos->referencia = $permisoModulo->id;
            $permisos->descripcion = "Ver boton cambio de ScopeGroup del CM por Intraway en Multiconsulta";
            $permisos->save();
            $permisos = new Permiso;
            $permisos->nombre = "Arbol de Decisiones";
            $permisos->slug = "submodulo.multiconsulta.arbol-decisiones.view";
            $permisos->tipo = "Submodulo";
            $permisos->imagen = "default.png";
            $permisos->referencia = $permisoModulo->id;
            $permisos->descripcion = "Ver boton arbol de decisiones en Multiconsulta";
            $permisos->save();
        #END MULTICONSULTA
          
        #ARBOL DE DECISIONES
            $permisoModulo = new Permiso;
            $permisoModulo->nombre = "Arbol de Deciciones";
            $permisoModulo->slug = "modulo.arbol-decision.index";
            $permisoModulo->tipo = "Modulo";
            $permisoModulo->imagen = "default.png";
            $permisoModulo->referencia = null;
            $permisoModulo->descripcion = "Ver Modulo de Arbol de Decisiones";
            $permisoModulo->save();
            $permisos = new Permiso;
            $permisos->nombre = "Listar pasos del Arbol de Decisiones";
            $permisos->slug = "submodulo.arbol-decision.list";
            $permisos->tipo = "Submodulo";
            $permisos->imagen = "default.png";
            $permisos->referencia = $permisoModulo->id;
            $permisos->descripcion = "Listar pasos del Arbol de Decisiones";
            $permisos->save();
            $permisos = new Permiso;
            $permisos->nombre = "Ver pasos del Arbol de Decisiones";
            $permisos->slug = "submodulo.arbol-decision.estructura";
            $permisos->tipo = "Submodulo";
            $permisos->imagen = "default.png";
            $permisos->referencia = $permisoModulo->id;
            $permisos->descripcion = "Ver pasos del Arbol de Decisiones";
            $permisos->save();
            $permisos = new Permiso;
            $permisos->nombre = "Crear pasos en el Arbol de Decisiones";
            $permisos->slug = "submodulo.arbol-decision.store";
            $permisos->tipo = "Submodulo";
            $permisos->imagen = "default.png";
            $permisos->referencia = $permisoModulo->id;
            $permisos->descripcion = "Crear pasos en el  Arbol de Decisiones";
            $permisos->save();
            $permisos = new Permiso;
            $permisos->nombre = "Editar pasos del Arbol de Decisiones";
            $permisos->slug = "submodulo.arbol-decision.edit";
            $permisos->tipo = "Submodulo";
            $permisos->imagen = "default.png";
            $permisos->referencia = $permisoModulo->id;
            $permisos->descripcion = "Editar pasos del Arbol de Decisiones";
            $permisos->save();
            $permisos = new Permiso;
            $permisos->nombre = "Actualizar pasos en el Arbol de Decisiones";
            $permisos->slug = "submodulo.arbol-decision.update";
            $permisos->tipo = "Submodulo";
            $permisos->imagen = "default.png";
            $permisos->referencia = $permisoModulo->id;
            $permisos->descripcion = "Actualizar pasos en el Arbol de Decisiones";
            $permisos->save();
            $permisos = new Permiso;
            $permisos->nombre = "Eliminar pasos en el Arbol de Decisiones";
            $permisos->slug = "submodulo.arbol-decision.delete";
            $permisos->tipo = "Submodulo";
            $permisos->imagen = "default.png";
            $permisos->referencia = $permisoModulo->id;
            $permisos->descripcion = "Eliminar  pasos en el Arbol de Decisiones";
            $permisos->save();
        #END ARBOL DE DECISIONES

        #LLAMADAS
            $permisoModulo = new Permiso;
            $permisoModulo->nombre = "Llamadas";
            $permisoModulo->slug = "modulo.llamadas.index";
            $permisoModulo->tipo = "Modulo";
            $permisoModulo->imagen = "default.png";
            $permisoModulo->referencia = null;
            $permisoModulo->descripcion = "Ver Modulo de Llamadas en el sistema";
            $permisoModulo->save();
        #END LLAMADAS
    }
}
